[theme]
primaryColor = "#4B8BBE"                # Azul Python
backgroundColor = "#F5F5F5"             # Gris muy claro
secondaryBackgroundColor = "#FFFFFF"    # Blanco
textColor = "#333333"                   # Gris oscuro
font = "sans serif"
