[theme]
# Fondo general oscuro
backgroundColor = "#0E1117"
# Fondo de cabeceras/controles
secondaryBackgroundColor = "#1A1A2E"
# Color principal de botones y resaltados
primaryColor = "#1E90FF"
# Color de texto claro para contraste
textColor = "#FFFFFF"
# Fuente neutra
font = "sans serif"
